# Generated by Django 3.2.6 on 2023-12-26 23:05

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户账号-用户唯一标识')),
                ('username', models.CharField(default='用户<built-in function id>', max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('avatar', models.ImageField(default='images/avatar/default.jpg', upload_to='images/avatar', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sign', models.CharField(default=user.models.default_sign, max_length=50, verbose_name='个人签名')),
                ('info', models.CharField(default='这个人很懒，还没有留下任何东西~~~', max_length=150, verbose_name='个人简介')),
            ],
            options={
                'db_table': 'user_User',
            },
        ),
    ]
