// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.0
// source: api/verifyCodeSystem/verifyCodeSystem.proto

package verifyCodeSystem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TYPE int32

const (
	TYPE_DEFAULT TYPE = 0
	TYPE_DIGIT   TYPE = 1
	TYPE_LETTER  TYPE = 2
	TYPE_MIXED   TYPE = 3
)

// Enum value maps for TYPE.
var (
	TYPE_name = map[int32]string{
		0: "DEFAULT",
		1: "DIGIT",
		2: "LETTER",
		3: "MIXED",
	}
	TYPE_value = map[string]int32{
		"DEFAULT": 0,
		"DIGIT":   1,
		"LETTER":  2,
		"MIXED":   3,
	}
)

func (x TYPE) Enum() *TYPE {
	p := new(TYPE)
	*p = x
	return p
}

func (x TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_api_verifyCodeSystem_verifyCodeSystem_proto_enumTypes[0].Descriptor()
}

func (TYPE) Type() protoreflect.EnumType {
	return &file_api_verifyCodeSystem_verifyCodeSystem_proto_enumTypes[0]
}

func (x TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TYPE.Descriptor instead.
func (TYPE) EnumDescriptor() ([]byte, []int) {
	return file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDescGZIP(), []int{0}
}

// 接口请求参数结构
type GetVerifyCodeSystemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 验证码长度
	Length int32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	// 验证码类型
	Type TYPE `protobuf:"varint,2,opt,name=type,proto3,enum=api.verifyCodeSystem.TYPE" json:"type,omitempty"`
}

func (x *GetVerifyCodeSystemRequest) Reset() {
	*x = GetVerifyCodeSystemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_verifyCodeSystem_verifyCodeSystem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVerifyCodeSystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeSystemRequest) ProtoMessage() {}

func (x *GetVerifyCodeSystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCodeSystem_verifyCodeSystem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeSystemRequest.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeSystemRequest) Descriptor() ([]byte, []int) {
	return file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDescGZIP(), []int{0}
}

func (x *GetVerifyCodeSystemRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetVerifyCodeSystemRequest) GetType() TYPE {
	if x != nil {
		return x.Type
	}
	return TYPE_DEFAULT
}

// 接口返回值结构
type GetVerifyCodeSystemReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetVerifyCodeSystemReply) Reset() {
	*x = GetVerifyCodeSystemReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_verifyCodeSystem_verifyCodeSystem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVerifyCodeSystemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeSystemReply) ProtoMessage() {}

func (x *GetVerifyCodeSystemReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCodeSystem_verifyCodeSystem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeSystemReply.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeSystemReply) Descriptor() ([]byte, []int) {
	return file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDescGZIP(), []int{1}
}

func (x *GetVerifyCodeSystemReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_api_verifyCodeSystem_verifyCodeSystem_proto protoreflect.FileDescriptor

var file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x22, 0x64, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x54,
	0x59, 0x50, 0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2e, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x2a, 0x35, 0x0a, 0x04, 0x54, 0x59, 0x50,
	0x45, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x44, 0x49, 0x47, 0x49, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x45, 0x54,
	0x54, 0x45, 0x52, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x49, 0x58, 0x45, 0x44, 0x10, 0x03,
	0x32, 0x8b, 0x01, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x77, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x30, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x50,
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x01, 0x5a, 0x36, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x3b,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDescOnce sync.Once
	file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDescData = file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDesc
)

func file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDescGZIP() []byte {
	file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDescOnce.Do(func() {
		file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDescData)
	})
	return file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDescData
}

var file_api_verifyCodeSystem_verifyCodeSystem_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_verifyCodeSystem_verifyCodeSystem_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_verifyCodeSystem_verifyCodeSystem_proto_goTypes = []interface{}{
	(TYPE)(0),                          // 0: api.verifyCodeSystem.TYPE
	(*GetVerifyCodeSystemRequest)(nil), // 1: api.verifyCodeSystem.GetVerifyCodeSystemRequest
	(*GetVerifyCodeSystemReply)(nil),   // 2: api.verifyCodeSystem.GetVerifyCodeSystemReply
}
var file_api_verifyCodeSystem_verifyCodeSystem_proto_depIdxs = []int32{
	0, // 0: api.verifyCodeSystem.GetVerifyCodeSystemRequest.type:type_name -> api.verifyCodeSystem.TYPE
	1, // 1: api.verifyCodeSystem.VerifyCodeSystem.GetVerifyCodeSystem:input_type -> api.verifyCodeSystem.GetVerifyCodeSystemRequest
	2, // 2: api.verifyCodeSystem.VerifyCodeSystem.GetVerifyCodeSystem:output_type -> api.verifyCodeSystem.GetVerifyCodeSystemReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_verifyCodeSystem_verifyCodeSystem_proto_init() }
func file_api_verifyCodeSystem_verifyCodeSystem_proto_init() {
	if File_api_verifyCodeSystem_verifyCodeSystem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_verifyCodeSystem_verifyCodeSystem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVerifyCodeSystemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_verifyCodeSystem_verifyCodeSystem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVerifyCodeSystemReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_verifyCodeSystem_verifyCodeSystem_proto_goTypes,
		DependencyIndexes: file_api_verifyCodeSystem_verifyCodeSystem_proto_depIdxs,
		EnumInfos:         file_api_verifyCodeSystem_verifyCodeSystem_proto_enumTypes,
		MessageInfos:      file_api_verifyCodeSystem_verifyCodeSystem_proto_msgTypes,
	}.Build()
	File_api_verifyCodeSystem_verifyCodeSystem_proto = out.File
	file_api_verifyCodeSystem_verifyCodeSystem_proto_rawDesc = nil
	file_api_verifyCodeSystem_verifyCodeSystem_proto_goTypes = nil
	file_api_verifyCodeSystem_verifyCodeSystem_proto_depIdxs = nil
}
