// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: api/verifyCodeSystem/verifyCodeSystem.proto

package verifyCodeSystem

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VerifyCodeSystem_GetVerifyCodeSystem_FullMethodName = "/api.verifyCodeSystem.VerifyCodeSystem/GetVerifyCodeSystem"
)

// VerifyCodeSystemClient is the client API for VerifyCodeSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifyCodeSystemClient interface {
	GetVerifyCodeSystem(ctx context.Context, in *GetVerifyCodeSystemRequest, opts ...grpc.CallOption) (*GetVerifyCodeSystemReply, error)
}

type verifyCodeSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifyCodeSystemClient(cc grpc.ClientConnInterface) VerifyCodeSystemClient {
	return &verifyCodeSystemClient{cc}
}

func (c *verifyCodeSystemClient) GetVerifyCodeSystem(ctx context.Context, in *GetVerifyCodeSystemRequest, opts ...grpc.CallOption) (*GetVerifyCodeSystemReply, error) {
	out := new(GetVerifyCodeSystemReply)
	err := c.cc.Invoke(ctx, VerifyCodeSystem_GetVerifyCodeSystem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifyCodeSystemServer is the server API for VerifyCodeSystem service.
// All implementations must embed UnimplementedVerifyCodeSystemServer
// for forward compatibility
type VerifyCodeSystemServer interface {
	GetVerifyCodeSystem(context.Context, *GetVerifyCodeSystemRequest) (*GetVerifyCodeSystemReply, error)
	mustEmbedUnimplementedVerifyCodeSystemServer()
}

// UnimplementedVerifyCodeSystemServer must be embedded to have forward compatible implementations.
type UnimplementedVerifyCodeSystemServer struct {
}

func (UnimplementedVerifyCodeSystemServer) GetVerifyCodeSystem(context.Context, *GetVerifyCodeSystemRequest) (*GetVerifyCodeSystemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerifyCodeSystem not implemented")
}
func (UnimplementedVerifyCodeSystemServer) mustEmbedUnimplementedVerifyCodeSystemServer() {}

// UnsafeVerifyCodeSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifyCodeSystemServer will
// result in compilation errors.
type UnsafeVerifyCodeSystemServer interface {
	mustEmbedUnimplementedVerifyCodeSystemServer()
}

func RegisterVerifyCodeSystemServer(s grpc.ServiceRegistrar, srv VerifyCodeSystemServer) {
	s.RegisterService(&VerifyCodeSystem_ServiceDesc, srv)
}

func _VerifyCodeSystem_GetVerifyCodeSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerifyCodeSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyCodeSystemServer).GetVerifyCodeSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifyCodeSystem_GetVerifyCodeSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyCodeSystemServer).GetVerifyCodeSystem(ctx, req.(*GetVerifyCodeSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerifyCodeSystem_ServiceDesc is the grpc.ServiceDesc for VerifyCodeSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerifyCodeSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.verifyCodeSystem.VerifyCodeSystem",
	HandlerType: (*VerifyCodeSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVerifyCodeSystem",
			Handler:    _VerifyCodeSystem_GetVerifyCodeSystem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/verifyCodeSystem/verifyCodeSystem.proto",
}
